# **Install**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
pip install newspaper3k

Collecting newspaper3k
  Downloading newspaper3k-0.2.8-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: beautifulsoup4>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (4.13.5)
Requirement already satisfied: Pillow>=3.3.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (11.3.0)
Requirement already satisfied: PyYAML>=3.11 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.3)
Collecting cssselect>=0.9.2 (from newspaper3k)
  Downloading cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: lxml>=3.6.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (6.0.3)
Requirement already satisfied: nltk>=3.2.1 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (3.9.1)
Requirement already satisfied: requests>=2.10.0 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.32.4)
Collecting feedparser>=5.2.1 (from newspaper3k)
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Collecting tldextract>=2.0.1 (from newspaper3k)
  Downloading tldextract-5.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting feedfinder2>=0.0.4 (from newspaper3k)
  Downloading feedfinder2-0.0.4.tar.gz (3.3 kB)
  Preparing metadata (setup.py) ... done
Collecting jieba3k>=0.35.1 (from newspaper3k)
  Downloading jieba3k-0.35.1.zip (7.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 47.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from newspaper3k) (2.9.0.post0)
Collecting tinysegmenter==0.3 (from newspaper3k)
  Downloading tinysegmenter-0.3.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.4.1->newspaper3k) (4.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from feedfinder2>=0.0.4->newspaper3k) (1.17.0)
Collecting sgmllib3k (from feedparser>=5.2.1->newspaper3k)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.2.1->newspaper3k) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.10.0->newspaper3k) (2026.2.25)
Collecting requests-file>=1.4 (from tldextract>=2.0.1->newspaper3k)
  Downloading requests_file-3.0.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: filelock>=3.0.8 in /usr/local/lib/python3.12/dist-packages (from tldextract>=2.0.1->newspaper3k) (3.25.2)
Downloading newspaper3k-0.2.8-py3-none-any.whl (211 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 18.1 MB/s eta 0:00:00
Downloading cssselect-1.4.0-py3-none-any.whl (18 kB)
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 8.6 MB/s eta 0:00:00
Downloading tldextract-5.3.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.9/105.9 kB 11.3 MB/s eta 0:00:00
Downloading requests_file-3.0.1-py2.py3-none-any.whl (4.5 kB)
Building wheels for collected packages: tinysegmenter, feedfinder2, jieba3k, sgmllib3k
  Building wheel for tinysegmenter (setup.py) ... done
  Created wheel for tinysegmenter: filename=tinysegmenter-0.3-py3-none-any.whl size=13540 sha256=ceaf5383a97bdf184fe453916bbc043d02745bc663f0f21ba6658683a9a91345
  Stored in directory: /root/.cache/pip/wheels/a5/91/9f/00d66475960891a64867914273fcaf78df6cb04d905b104a2a
  Building wheel for feedfinder2 (setup.py) ... done
  Created wheel for feedfinder2: filename=feedfinder2-0.0.4-py3-none-any.whl size=3341 sha256=d355718a89aaa77c0e58061c3b3c27f0bbaf706f0fe873da00cc3ac680a2cc37
  Stored in directory: /root/.cache/pip/wheels/9f/9f/fb/364871d7426d3cdd4d293dcf7e53d97f160c508b2ccf00cc79
  Building wheel for jieba3k (setup.py) ... done
  Created wheel for jieba3k: filename=jieba3k-0.35.1-py3-none-any.whl size=7398380 sha256=edc6081bf57a5fed34c798eb4bfda90086c12d7c0079ee12db7cc1cd271cd1e6
  Stored in directory: /root/.cache/pip/wheels/26/72/f7/fff392a8d4ea988dea4ccf9788599d09462a7f5e51e04f8a92
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=b5d5e9c33264861aa7291629928844b764b7e49f2e594b324082ac6a7e4888e5
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built tinysegmenter feedfinder2 jieba3k sgmllib3k
Installing collected packages: tinysegmenter, sgmllib3k, jieba3k, feedparser, cssselect, requests-file, feedfinder2, tldextract, newspaper3k
Successfully installed cssselect-1.4.0 feedfinder2-0.0.4 feedparser-6.0.12 jieba3k-0.35.1 newspaper3k-0.2.8 requests-file-3.0.1 sgmllib3k-1.0.0 tinysegmenter-0.3 tldextract-5.3.1

In [3]:
!pip install lxml_html_clean

Collecting lxml_html_clean
  Downloading lxml_html_clean-0.4.4-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from lxml_html_clean) (6.0.3)
Downloading lxml_html_clean-0.4.4-py3-none-any.whl (14 kB)
Installing collected packages: lxml_html_clean
Successfully installed lxml_html_clean-0.4.4

In [4]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [5]:
!pip install playwright -q
!playwright install chromium --with-deps

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 23.1 MB/s eta 0:00:00
Installing dependencies...
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:3 https://cli.github.com/packages stable/main amd64 Packages [354 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [89.0 kB]
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.0 MB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,623 kB]
Get:12 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,232 kB]
Get:15 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,311 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,264 kB]
Get:18 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,970 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [35.9 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,015 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,929 kB]
Fetched 39.0 MB in 4s (10.9 MB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libfreetype6 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libglib2.0-0 is already the newest version (2.72.4-0ubuntu2.9).
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
The following additional packages will be installed:
  libatk1.0-data xfonts-encodings xfonts-utils
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma at-spi2-core
The following NEW packages will be installed:
  fonts-freefont-ttf fonts-ipafont-gothic fonts-noto-color-emoji
  fonts-tlwg-loma-otf fonts-unifont fonts-wqy-zenhei libatk-bridge2.0-0
  libatk1.0-0 libatk1.0-data libatspi2.0-0 libxcomposite1 xfonts-cyrillic
  xfonts-encodings xfonts-scalable xfonts-utils
0 upgraded, 15 newly installed, 0 to remove and 38 not upgraded.
Need to get 28.6 MB of archives.
After this operation, 68.7 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-freefont-ttf all 20120503-10build1 [2,388 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.22.04.1 [10.0 MB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-unifont all 1:14.0.01-1 [3,551 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-encodings all 1:1.0.5-0ubuntu2 [578 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-utils amd64 1:7.7+6build2 [94.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/universe amd64 xfonts-cyrillic all 1:1.0.5 [386 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 xfonts-scalable all 1:1.0.3-1.2ubuntu1 [306 kB]
Fetched 28.6 MB in 1s (24.3 MB/s)
Selecting previously unselected package fonts-ipafont-gothic.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-fonts-ipafont-gothic_00303-21ubuntu1_all.deb ...
Unpacking fonts-ipafont-gothic (00303-21ubuntu1) ...
Selecting previously unselected package fonts-freefont-ttf.
Preparing to unpack .../01-fonts-freefont-ttf_20120503-10build1_all.deb ...
Unpacking fonts-freefont-ttf (20120503-10build1) ...
Selecting previously unselected package fonts-noto-color-emoji.
Preparing to unpack .../02-fonts-noto-color-emoji_2.047-0ubuntu0.22.04.1_all.deb ...
Unpacking fonts-noto-color-emoji (2.047-0ubuntu0.22.04.1) ...
Selecting previously unselected package fonts-tlwg-loma-otf.
Preparing to unpack .../03-fonts-tlwg-loma-otf_1%3a0.7.3-1_all.deb ...
Unpacking fonts-tlwg-loma-otf (1:0.7.3-1) ...
Selecting previously unselected package fonts-unifont.
Preparing to unpack .../04-fonts-unifont_1%3a14.0.01-1_all.deb ...
Unpacking fonts-unifont (1:14.0.01-1) ...
Selecting previously unselected package fonts-wqy-zenhei.
Preparing to unpack .../05-fonts-wqy-zenhei_0.9.45-8_all.deb ...
Unpacking fonts-wqy-zenhei (0.9.45-8) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../06-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../07-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatspi2.0-0:amd64.
Preparing to unpack .../08-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../09-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../10-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package xfonts-encodings.
Preparing to unpack .../11-xfonts-encodings_1%3a1.0.5-0ubuntu2_all.deb ...
Unpacking xfonts-encodings (1:1.0.5-0ubuntu2) ...
Selecting previously unselected package xfonts-utils.
Preparing to unpack .../12-xfonts-utils_1%3a7.7+6build2_amd64.deb ...
Unpacking xfonts-utils (1:7.7+6build2) ...
Selecting previously unselected package xfonts-cyrillic.
Preparing to unpack .../13-xfonts-cyrillic_1%3a1.0.5_all.deb ...
Unpacking xfonts-cyrillic (1:1.0.5) ...
Selecting previously unselected package xfonts-scalable.
Preparing to unpack .../14-xfonts-scalable_1%3a1.0.3-1.2ubuntu1_all.deb ...
Unpacking xfonts-scalable (1:1.0.3-1.2ubuntu1) ...
Setting up fonts-noto-color-emoji (2.047-0ubuntu0.22.04.1) ...
Setting up fonts-wqy-zenhei (0.9.45-8) ...
Setting up fonts-freefont-ttf (20120503-10build1) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up fonts-tlwg-loma-otf (1:0.7.3-1) ...
Setting up xfonts-encodings (1:1.0.5-0ubuntu2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-ipafont-gothic (00303-21ubuntu1) ...
update-alternatives: using /usr/share/fonts/opentype/ipafont-gothic/ipag.ttf to provide /usr/share/fonts/truetype/fonts-japanese-gothic.ttf (fonts-japanese-gothic.ttf) in auto mode
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up fonts-unifont (1:14.0.01-1) ...
Setting up xfonts-utils (1:7.7+6build2) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up xfonts-cyrillic (1:1.0.5) ...
Setting up xfonts-scalable (1:1.0.3-1.2ubuntu1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:10018) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 340.0s167.3 MiB [] 0% 62.0s167.3 MiB [] 0% 27.0s167.3 MiB [] 0% 22.0s167.3 MiB [] 0% 20.7s167.3 MiB [] 0% 16.5s167.3 MiB [] 1% 9.6s167.3 MiB [] 1% 8.8s167.3 MiB [] 2% 6.9s167.3 MiB [] 2% 6.7s167.3 MiB [] 2% 6.8s167.3 MiB [] 3% 5.7s167.3 MiB [] 4% 5.1s167.3 MiB [] 4% 4.6s167.3 MiB [] 5% 4.2s167.3 MiB [] 6% 3.9s167.3 MiB [] 7% 3.7s167.3 MiB [] 7% 3.6s167.3 MiB [] 8% 3.4s167.3 MiB [] 9% 3.2s167.3 MiB [] 10% 3.1s167.3 MiB [] 11% 2.9s167.3 MiB [] 12% 2.8s167.3 MiB [] 13% 2.7s167.3 MiB [] 14% 2.6s167.3 MiB [] 15% 2.5s167.3 MiB [] 16% 2.5s167.3 MiB [] 17% 2.4s167.3 MiB [] 18% 2.3s167.3 MiB [] 19% 2.3s167.3 MiB [] 20% 2.2s167.3 MiB [] 21% 2.2s167.3 MiB [] 22% 2.1s167.3 MiB [] 23% 2.1s167.3 MiB [] 24% 2.0s167.3 MiB [] 25% 1.9s167.3 MiB [] 26% 1.9s167.3 MiB [] 27% 1.9s167.3 MiB [] 28% 1.8s167.3 MiB [] 29% 1.8s167.3 MiB [] 31% 1.8s167.3 MiB [] 31% 1.9s167.3 MiB [] 33% 1.8s167.3 MiB [] 34% 1.7s167.3 MiB [] 35% 1.7s167.3 MiB [] 36% 1.6s167.3 MiB [] 38% 1.6s167.3 MiB [] 39% 1.5s167.3 MiB [] 40% 1.5s167.3 MiB [] 41% 1.5s167.3 MiB [] 41% 1.4s167.3 MiB [] 42% 1.4s167.3 MiB [] 43% 1.4s167.3 MiB [] 44% 1.3s167.3 MiB [] 45% 1.3s167.3 MiB [] 46% 1.3s167.3 MiB [] 47% 1.3s167.3 MiB [] 48% 1.2s167.3 MiB [] 50% 1.2s167.3 MiB [] 51% 1.2s167.3 MiB [] 52% 1.1s167.3 MiB [] 53% 1.1s167.3 MiB [] 54% 1.1s167.3 MiB [] 55% 1.0s167.3 MiB [] 56% 1.0s167.3 MiB [] 57% 1.0s167.3 MiB [] 58% 1.0s167.3 MiB [] 59% 0.9s167.3 MiB [] 60% 0.9s167.3 MiB [] 61% 0.9s167.3 MiB [] 62% 0.8s167.3 MiB [] 63% 0.8s167.3 MiB [] 64% 0.8s167.3 MiB [] 65% 0.8s167.3 MiB [] 66% 0.7s167.3 MiB [] 67% 0.7s167.3 MiB [] 68% 0.7s167.3 MiB [] 69% 0.7s167.3 MiB [] 70% 0.7s167.3 MiB [] 71% 0.6s167.3 MiB [] 72% 0.6s167.3 MiB [] 73% 0.6s167.3 MiB [] 74% 0.6s167.3 MiB [] 75% 0.5s167.3 MiB [] 76% 0.5s167.3 MiB [] 77% 0.5s167.3 MiB [] 78% 0.5s167.3 MiB [] 79% 0.5s167.3 MiB [] 80% 0.4s167.3 MiB [] 82% 0.4s167.3 MiB [] 84% 0.4s167.3 MiB [] 85% 0.3s167.3 MiB [] 86% 0.3s167.3 MiB [] 87% 0.3s167.3 MiB [] 88% 0.3s167.3 MiB [] 89% 0.2s167.3 MiB [] 90% 0.2s167.3 MiB [] 91% 0.2s167.3 MiB [] 92% 0.2s167.3 MiB [] 93% 0.1s167.3 MiB [] 94% 0.1s167.3 MiB [] 95% 0.1s167.3 MiB [] 96% 0.1s167.3 MiB [] 98% 0.0s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:10069) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 2% 0.7s2.3 MiB [] 6% 0.5s2.3 MiB [] 13% 0.3s2.3 MiB [] 26% 0.2s2.3 MiB [] 52% 0.1s2.3 MiB [] 81% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:10082) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 44.5s110.9 MiB [] 0% 15.3s110.9 MiB [] 0% 17.7s110.9 MiB [] 0% 13.9s110.9 MiB [] 0% 11.1s110.9 MiB [] 1% 6.5s110.9 MiB [] 2% 5.0s110.9 MiB [] 3% 4.4s110.9 MiB [] 3% 4.0s110.9 MiB [] 4% 3.4s110.9 MiB [] 5% 3.1s110.9 MiB [] 6% 3.3s110.9 MiB [] 7% 3.0s110.9 MiB [] 8% 2.8s110.9 MiB [] 9% 2.6s110.9 MiB [] 10% 2.6s110.9 MiB [] 10% 2.7s110.9 MiB [] 11% 2.7s110.9 MiB [] 12% 2.6s110.9 MiB [] 13% 2.6s110.9 MiB [] 14% 2.5s110.9 MiB [] 15% 2.5s110.9 MiB [] 16% 2.4s110.9 MiB [] 16% 2.3s110.9 MiB [] 17% 2.3s110.9 MiB [] 18% 2.3s110.9 MiB [] 19% 2.3s110.9 MiB [] 20% 2.2s110.9 MiB [] 21% 2.2s110.9 MiB [] 22% 2.1s110.9 MiB [] 22% 2.2s110.9 MiB [] 23% 2.2s110.9 MiB [] 23% 2.1s110.9 MiB [] 24% 2.1s110.9 MiB [] 25% 2.1s110.9 MiB [] 26% 2.0s110.9 MiB [] 26% 2.1s110.9 MiB [] 27% 2.1s110.9 MiB [] 28% 2.0s110.9 MiB [] 28% 2.1s110.9 MiB [] 29% 2.1s110.9 MiB [] 30% 2.0s110.9 MiB [] 31% 1.9s110.9 MiB [] 33% 1.9s110.9 MiB [] 33% 1.8s110.9 MiB [] 35% 1.8s110.9 MiB [] 36% 1.7s110.9 MiB [] 37% 1.7s110.9 MiB [] 38% 1.6s110.9 MiB [] 39% 1.6s110.9 MiB [] 40% 1.6s110.9 MiB [] 42% 1.5s110.9 MiB [] 43% 1.5s110.9 MiB [] 43% 1.4s110.9 MiB [] 45% 1.4s110.9 MiB [] 46% 1.3s110.9 MiB [] 47% 1.3s110.9 MiB [] 49% 1.2s110.9 MiB [] 50% 1.2s110.9 MiB [] 51% 1.1s110.9 MiB [] 53% 1.1s110.9 MiB [] 54% 1.0s110.9 MiB [] 56% 1.0s110.9 MiB [] 57% 0.9s110.9 MiB [] 59% 0.9s110.9 MiB [] 60% 0.9s110.9 MiB [] 61% 0.9s110.9 MiB [] 62% 0.8s110.9 MiB [] 63% 0.8s110.9 MiB [] 65% 0.8s110.9 MiB [] 66% 0.7s110.9 MiB [] 67% 0.7s110.9 MiB [] 68% 0.7s110.9 MiB [] 69% 0.7s110.9 MiB [] 70% 0.6s110.9 MiB [] 71% 0.6s110.9 MiB [] 72% 0.6s110.9 MiB [] 73% 0.6s110.9 MiB [] 74% 0.5s110.9 MiB [] 76% 0.5s110.9 MiB [] 77% 0.5s110.9 MiB [] 78% 0.5s110.9 MiB [] 79% 0.4s110.9 MiB [] 80% 0.4s110.9 MiB [] 81% 0.4s110.9 MiB [] 82% 0.4s110.9 MiB [] 83% 0.3s110.9 MiB [] 84% 0.3s110.9 MiB [] 86% 0.3s110.9 MiB [] 87% 0.3s110.9 MiB [] 88% 0.2s110.9 MiB [] 89% 0.2s110.9 MiB [] 90% 0.2s110.9 MiB [] 91% 0.2s110.9 MiB [] 92% 0.2s110.9 MiB [] 93% 0.1s110.9 MiB [] 94% 0.1s110.9 MiB [] 95% 0.1s110.9 MiB [] 97% 0.1s110.9 MiB [] 98% 0.0s110.9 MiB [] 99% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208

In [6]:
import newspaper
from newspaper import news_pool
from newspaper import Article

# **Dataset Individu**

In [ ]:
import pandas as pd

df_tambah = pd.read_csv('/content/drive/My Drive/BPJS_Shafa.csv')
df_tambah

,No,Link,Sentiment,Penerbit,Tag
0,1,https://rejogja.republika.co.id/berita/ta8twq2...,Netral,Republika,Kebijakan
1,2,https://www.kompas.tv/regional/655861/urus-pem...,Negatif,Kompas,Sosial
2,3,https://www.gesuri.id/pemerintahan/bpjs-pbi-no...,Negatif,Gesuri,Pelayanan
3,4,https://nasional.kompas.com/read/2026/03/09/20...,Positif,Kompas,Kebijakan
4,5,https://bantulkab.go.id/berita/detail/7383/dis...,Netral,bantulkab,Kebijakan
...,...,...,...,...,...
95,96,https://news.detik.com/berita/d-8343050/dirut-...,Netral,Detik,Kebijakan
96,97,https://www.tempo.co/ekonomi/mengenal-apa-itu-...,Netral,Tempo,Kebijakan
97,98,https://finansial.bisnis.com/read/20260331/215...,Positif,Bisnis,Kebijakan
98,99,https://banten.antaranews.com/berita/377374/50...,Positif,Antara,Pelayanan
99,100,https://nasional.kompas.com/read/2020/05/15/10...,Negatif,Kompas,Opini

In [ ]:
list_of_urls = df_tambah['Link'].tolist()
list_of_urls

['https://rejogja.republika.co.id/berita/ta8twq282/menkes-pastikan-bpjs-lakukan-sosialisasi-jika-kepesertaan-pbi-jkn-kembali-berubah',
 'https://www.kompas.tv/regional/655861/urus-pemindahan-data-desil-bpjs-pbi-oknum-asn-dinsos-lebak-lakukan-pungli-ke-warga',
 'https://www.gesuri.id/pemerintahan/bpjs-pbi-nonaktif-warga-landak-kesulitan-berobat-mengadu-ke-cornelis-b2pQoZbewe',
 'https://nasional.kompas.com/read/2026/03/09/20240271/peserta-bpjs-pbi-yang-dinonaktifkan-masih-bisa-terlayani-selama-lebaran-2026',
 'https://bantulkab.go.id/berita/detail/7383/diskominfo@bantulkab.go.id',
 'https://www.kompas.tv/nasional/650201/dpr-bahas-kisruh-pbi-dinonaktifkan-ini-klarifikasi-menkes-dirut-bpjs-kesehatan',
 'https://bansos.medanaktual.com/kenapa-kepesertaan-pbi-bpjs-bisa-dinonaktifkan-ini-penjelasannya/',
 'https://health.detik.com/berita-detikhealth/d-8392134/bpjs-kesehatan-pastikan-peserta-pbi-yang-sempat-nonaktif-tetap-dilayani-selama-mudik',
 'https://pekanbaru.tribunnews.com/riau-region/1102392/dinsos-kampar-ungkap-penonaktifan-47-ribuan-bpjs-pbi-karena-desil-tiap-daerah-disamaratakan',
 'https://finansial.bisnis.com/read/20260310/215/1959312/dirut-baru-bpjs-kesehatan-peserta-pbi-nonaktif-berpenyakit-kronis-tetap-bisa-pakai-jkn-saat-mudik',
 'https://www.radarbangsa.com/news/59453/bpjs-kesehatan-pastikan-peserta-pbi-nonaktif-tetap-dilayani-selama-mudik',
 'https://koran-jakarta.com/2026-03-10/bpjs-kesehatan-tegaskan-peserta-pbi-nonaktif-tetap-dilayani-selama-mudik',
 'https://www.oborkeadilan.com/bpjs-kesehatan-jamin-layanan-terus-untuk-peserta-pbi-yang-nonaktif-selama-mudik-lebaran',
 'https://news.ddtc.co.id/berita/nasional/1817220/11-juta-orang-dihapus-dari-daftar-pbi-jkn-purbaya-usul-begini',
 'https://video.tribunnews.com/news/911123/rieke-sentil-menkeu-purbaya-soal-data-bpjs-pbi-ini-bukan-kondisi-yang-baik-baik-saja',
 'https://dprd.kuningankab.go.id/berita/bpjs-pbi-dinonaktifkan-dprd-kuningan-minta-warga-tak-panik-dan-segera-perbarui-data',
 'https://rejogja.republika.co.id/berita/ta1k4p282/34143-peserta-pbi-bpjs-di-sleman-dinonaktifkan-alasannya-tak-lagi-masuk-desil-15',
 'https://www.kompas.tv/nasional/649962/relawan-kesehatan-kritik-persoalan-penonaktifan-pbi-data-kita-tidak-terintegrasi-penuh',
 'https://pers.droneemprit.id/sentimen-publik-terhadap-penonaktifan-pbi-bpjs-kesehatan/',
 'https://nasional.kompas.com/read/2020/07/02/12012541/pemerintah-pusat-akan-tanggung-iuran-pbi-bpjs-kesehatan-tahun-ini',
 'https://partainasdem.id/2026/03/09/kebijakan-pbi-bpjs-kesehatan-tidak-boleh-abaikan-masyarakat-rentan/',
 'https://harianjurnal.com/opini/10211-penonaktifan-peserta-bpjs-kategori-pbi-bijakkah',
 'https://manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3534-update-data-supaya-penerima-pbi-bpjs-kesehatan-tepat-sasaran',
 'https://www.telusur.co.id/detail/antara-opini-dan-ambisi-sorotan-terhadap-sikap-putu-artha-dalam-polemik-kebijakan-bpjs-pbi',
 'https://narasipost.com/opini/02/2026/karut-marut-bpjs-pbi-mengancam-kesehatan-rakyat/',
 'https://www.tintahijau.com/literasi/opini-kisruh-pbi-bpjs-kesehatan/',
 'https://www.tangerangnews.com/opini/read/57249/Ironi-BPJS-PBI-Melayani-Setengah-Hati',
 'https://smeru.or.id/id/research-id/kajian-dampak-bantuan-iuran-program-jaminan-kesehatan-pada-masyarakat-miskin-dan-tidak',
 'https://www.cna.id/indonesia/bpjs-pbi-tetap-aktif-tiga-bulan-dpr-44256',
 'https://www.manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3176-dampak-pandemi-ratusan-peserta-bpjs-mandiri-minta-pindah-ke-pbi',
 'https://beritaopini.id/2026/02/13/bpjs-pbi-dinonaktifkan-massal-mahasiswa-aktivis-hingga-ojol-nilai-negara-abai-hak-kesehatan-warga/',
 'https://gatradewata.com/bangga-angka-miskin-rendah-bpjs-pbi-dihapus-kok-dihidupkan-lagi-dari-apbd-gung-de-konyol/',
 'https://beritamerdeka.net/news/terbantu-jkn-petani-aceh-selatan-tak-khawatir-biaya-perawatan/index.html',
 'https://www.antaranews.com/berita/5413874/layanan-bpjs-pbi-tak-terhenti-warga-bersyukur-anaknya-bisa-cuci-darah',
 'https://denpasar.kompas.com/read/2026/02/10/164359578/walkot-denpasar-aktifkan-bpjs-pbi-masyarakat-merasa-sangat-terbantu?page=all',
 'https://www.tribun-maluku.com/edukasi-kepesertaan-pbi-jk-di-masohi-bpjs-kesehatan-kolaborasi-dengan-instansi-terkait/03/04/',
 'https://www.metrotvnews.com/play/kqYCdGde-reaktivasi-sementara-11-juta-peserta-bpjs-pbi-benarkah-sudah-cukup-beranda-nasional',
 'https://infopublik.id/kategori/nasional-sosial-budaya/958183/index.html',
 'https://www.harianjogja.com/read/2026/03/04/652/1248230/terbantu-jkn-pensiunan-ini-jalani-cuci-darah-tanpa-hambatan',
 'https://www.tempo.co/politik/pemerintah-aktifkan-kembali-625-ribu-penerima-bpjs-kesehatan-2125728',
 'https://www.metrotvnews.com/read/NOlC9PVv-mensos-verifikasi-11-juta-pbi-jkn-sudah-98-persen',
 'https://www.theindonesianinstitute.com/policy-talks-solusi-penonaktifan-kepesertaan-pbi-bpjs-kesehatan/',
 'https://www.medcom.id/ekonomi/bisnis/RkjBMx6k-mulai-2021-peserta-pbi-bpjs-kesehatan-ditanggung-pemerintah-pusat',
 'https://www.geriatri.co.id/artikel/2683/penyebab-bpjs-kesehatan-pbi-tidak-aktif-dan-cara-mengaktifkan-kembali',
 'https://www.netralnews.com/11013-peserta-pbi-bpjs-nonaktif-di-kuansing-akan-diverifikasi/TUlzUXlvcTkwTkJHYUNtYzYvaE5IZz09',
 'https://suarantb.com/2026/03/28/kurangi-beban-fiskal-daerah-lobar-usulkan-68-ribu-warga-jadi-pbi-bjps-kesehatan/',
 'https://faktakalbar.id/2026/03/31/izin-kemenkes-turun-layanan-cuci-darah-rsud-landak-terkendala-kerja-sama-bpjs/',
 'https://aceh.antaranews.com/berita/403810/pemprov-aceh-keluarkan-tiga-kelompok-masyarakat-dari-penerima-program-jka',
 'https://pekanbaru.tribunnews.com/riau-region/1102015/hamidah-kini-berhenti-kontrol-ke-dokter-kepesertaan-pbi-tak-kunjung-diaktifkan',
 'https://bantal.desa.id/artikel/2022/04/20/bpjs-kesehatan-tidak-menanggung-layanan-dan-penyakit-jenis-ini-lihat-daftarnya',
 'https://www.suarakeadilan.org/id/publikasi/suara-keadilan/lintas-berita/166-mempertanyakan-akses-rakyat-miskin-terhadap-jaminan-kesehatan-nasional',
 'https://info.medanaktual.com/kenapa-status-pbi-bpjs-berubah-jadi-nonaktif-yuk-cari-tahu-penyebabnya/',
 'https://www.kompas.tv/nasional/649605/13-5-juta-peserta-bpjs-pbi-dinonaktifkan-mensos-tak-ada-yang-dikurangi-tapi-direalokasi',
 'https://korankaltara.com/pbi-bpjs-banyak-tidak-aktif-warga-diminta-lapor',
 'https://www.antaranews.com/berita/1026716/kenaikan-iuran-bpjs-kesehatan-tidak-kurangi-peserta-pbi-di-mataram',
 'https://www.inibalikpapan.com/bpjs-pbi-tak-dihentikan-dpr-pastikan-warga-miskin-tetap-dilayani-selama-3-bulan-ke-depan/',
 'https://setkab.go.id/sidak-presiden-jokowi-temukan-lebih-banyak-peserta-bpjs-kesehatan-mandiri-daripada-pbi/',
 'https://pekanbaru.tribunnews.com/riau-region/1101984/pasien-pbi-bpjs-belum-diaktifkan-terpaksa-beralih-ke-obat-herbal-belum-bisa-kontrol-rutin',
 'https://www.metrotvnews.com/play/NnjCWMGW-warga-bekasi-dan-depok-padati-kantor-bpjs-untuk-mengaktifkan-kembali-pbijk',
 'https://nasional.kompas.com/read/2026/02/09/18401521/purbaya-kesal-bpjs-kesehatan-pbi-mendadak-dinonaktifkan-konyol-saya-rugi?page=all',
 'https://era.id/nasional/183383/pbi-non-aktif-picu-kemarahan-publik-bpjs-kesehatan-lempar-bola-panas-ke-rumah-sakit',
 'https://video.kompas.com/live/34808b196bdf5d3571cb2faf7a64ed9c/polemik-penonaktifan-bpjs-kesehatan-pbi-apa-jalan-keluarnya-obrolan-newsroom',
 'https://www.kompas.tv/nasional/649954/kisruh-bpjs-kesehatan-pbi-warga-dinonaktifkan-kemensos-lakukan-perombakan-kompas-siang',
 'https://www.tempo.co/ekonomi/bos-bpjs-kesehatan-jelaskan-alasan-7-3-juta-peserta-pbi-jkn-dinonaktifkan-1795353',
 'https://jogja.antaranews.com/berita/819773/bpjs-kesehatan-bayi-baru-lahir-dari-orang-tua-terdaftar-pbi-ditanggung-jkn',
 'https://wartakota.tribunnews.com/jakarta/882723/cerita-tia-bolak-balik-urus-bpjs-pbi-akui-kesal-karena-dinonaktifkan-tanpa-pemberitahuan?page=all',
 'https://pojokbanua.com/penyebab-polemik-bpjs-pbi-bagaimana-nasib-pasien-penyakit-berat/',
 'https://www.kompas.id/artikel/bpjs-kesehatan-pbi-milik-11-juta-warga-miskin-di-jateng-dinonaktifkan',
 'https://www.kompas.id/artikel/11-juta-peserta-pbi-jkn-dinonaktifkan-lebih-dari-100-pasien-cuci-darah-terdampak',
 'https://nasional.kontan.co.id/news/bpjs-kesehatan-catat-jumlah-peserta-pbi-968-juta-pengobatan-jantung-meningkat',
 'https://www.sinarharapan.net/kartu-pbi-tak-berlaku-pasien-miskin-tak-dapat-layanan-kesehatan/',
 'https://headlinekaltim.co/jarang-dipakai-berobat-apakah-benar-bpjs-kesehatan-pbi-bisa-diblokir/',
 'https://karangmulyo.kendalkab.go.id/kabardetail/d2dsNjloV2JZTFBEN2lSZUN1ZkhJUT09/segera-manfaatkan-bpjs-pbi-anda-minimal-3-bulan-sekali.html',
 'https://www.surabaya.go.id/id/berita/73952/pemkot-surabaya-imbau-peserta-pbi-jk-yang-tak-aktif-ajukan-pendaftaran-pbpu',
 'https://www.bpjsketenagakerjaan.go.id/berita/29164/Edy-Dorong-Kolaborasi-Untuk-Realisasikan-PBI-Untuk-Jamsostek',
 'https://www.bpjsketenagakerjaan.go.id/berita/27725/Kajian-aturan-PBI-jamsosketenagakerjaan-ditargetkan-rampung-tahun-ini',
 'https://www.manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3807-benarkah-warga-yang-tak-daftar-bpjs-kesehatan-akan-otomatis-terdaftar-kategori-pbi',
 'https://kemkes.go.id/id/penerima-bantuan-iuran-pbi-jaminan-kesehatan-nasional-jkn-di-daerah-istimewa-yogyakarta-sebanyak-1-572-154-jiwa',
 'https://nasional.kontan.co.id/news/bpjs-kesehatan-sebut-tak-ada-tambahan-peserta-penerima-bantuan-iuran-pbi-kesehatan',
 'https://www.antaranews.com/berita/3329355/kemensos-disabilitas-mental-diizinkan-jadi-peserta-pbi-bpjs-kesehatan',
 'https://www.pasuruankab.go.id/isiberita/37-495-peserta-pbin-di-kabupaten-pasuruan-dinonaktifkan',
 'https://www.tangerangkota.go.id/berita/detail/37237/wujudkan-pengobatan-kesehatan-gratis-pemkot-tangerang-bayarkan-367-476-warga-iuran-bpjs-kesehatan',
 'https://news.republika.co.id/berita/t9zkne458/ramai-pbi-jk-mendadak-nonaktif-mensos-rs-tak-boleh-menolak-pasien-cuci-darah',
 'https://health.detik.com/berita-detikhealth/d-8340126/30-pasien-cuci-darah-tak-bisa-berobat-imbas-status-pbi-bpjs-mendadak-non-aktif',
 'https://www.cnnindonesia.com/ekonomi/20260209173925-532-1326288/purbaya-soal-peserta-pbi-bpjs-cuci-darah-dinonaktifkan-kita-konyol',
 'https://www.netralnews.com/heboh-bpjs-kesehatan-pbi-tiba-tiba-nonaktif-ini-penjelasan-resminya/ZFJ2TFdxWnZaQzg3bEZXTVlGMk5zUT09',
 'https://www.liputan6.com/bisnis/read/6273347/ylki-kritik-penonaktifan-peserta-pbi-bpjs-kesehatan-pasien-rentan-jadi-korban',
 'https://www.kompas.tv/regional/650093/kacau-penonaktifan-13-5-juta-peserta-bpjs-pbi-picu-masalah-layanan-kesehatan-di-berbagai-daerah',
 'https://voi.id/bernas/558547/karut-marut-penonaktifan-peserta-bpjs-pbi-pemerintah-tak-pernah-mau-belajar',
 'https://www.bloombergtechnoz.com/detail-news/54933/kronologi-ancaman-gagal-bayar-bpjs-kesehatan-iuran-naik',
 'https://www.bbc.com/indonesia/articles/cn06g268n6vo',
 'https://fkkmk.ugm.ac.id/penyakit-jantung-dan-kanker-25-persen-duduki-pembiayaan-bpjs-kesehatan/',
 'https://www.liputan6.com/hot/read/5714785/bantuan-pbi-adalah-solusi-kesehatan-bagi-masyarakat-kurang-mampu-ini-penjelasannya',
 'https://jatim.antaranews.com/berita/690537/ada-lima-juta-orang-antre-jadi-peserta-pbi-jkn',
 'https://www.tempo.co/politik/sederet-fakta-jaminan-kesehatan-11-juta-orang-dicabut-2113363',
 'https://news.detik.com/berita/d-8343050/dirut-bpjs-buka-suara-usai-ramai-status-pbi-jk-warga-mendadak-nonaktif',
 'https://www.tempo.co/ekonomi/mengenal-apa-itu-pbi-jk-serta-kriteria-penerimanya-1189453',
 'https://finansial.bisnis.com/read/20260331/215/1963398/625221-peserta-bpjs-kesehatan-pbi-dapat-pemulihan-verifikasi-data-sudah-98',
 'https://banten.antaranews.com/berita/377374/500-warga-kota-serang-reaktivasi-bpjs-pbi-dari-11000-data-nonaktif',
 'https://nasional.kompas.com/read/2020/05/15/10194671/berbagai-alasan-dan-klaim-pemerintah-naikkan-iuran-bpjs-kesehatan']

In [ ]:
from os import link
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urlparse
import time
import json
import re
import random

session = requests.Session()

headers_list = [
    {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive"
    },
    {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive"
    }
]

article_details_list = []
failed_list = []
headers = random.choice(headers_list)


def clean_text(text):
    if text is None:
        return None
    text = str(text)
    text = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text if text else None


for i, row in df_tambah.iterrows():
    no = row.get("No")
    url = row.get("Link")
    sentiment = row.get("Sentiment")
    penerbit = row.get("Penerbit")
    tag = row.get("Tag")

    print(f"[{i+1}/{len(df_tambah)}] {url}")

    try:
        r = session.get(url, headers=headers, timeout=30)
        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")
        source = urlparse(url).netloc.replace("www.", "")

        # kalau kolom Penerbit kosong, pakai domain URL
        if pd.isna(penerbit) or not str(penerbit).strip():
            penerbit = source

        # ================= TITLE =================
        title = None

        if soup.title:
            title = soup.title.get_text(" ", strip=True)

        og_title = soup.find("meta", attrs={"property": "og:title"})
        if og_title and og_title.get("content"):
            title = og_title["content"].strip()

        # ================= SUMMARY =================
        summary = None

        meta_desc = soup.find("meta", attrs={"name": "description"})
        if meta_desc and meta_desc.get("content"):
            summary = meta_desc["content"].strip()

        if not summary:
            og_desc = soup.find("meta", attrs={"property": "og:description"})
            if og_desc and og_desc.get("content"):
                summary = og_desc["content"].strip()

        # ================= AUTHORS =================
        authors = None

        author_selectors = [
            ("meta", {"name": "author"}),
            ("meta", {"property": "author"}),
            ("meta", {"name": "article:author"}),
            ("meta", {"property": "article:author"})
        ]

        for tag_name, attrs in author_selectors:
            tag_author = soup.find(tag_name, attrs=attrs)
            if tag_author and tag_author.get("content"):
                authors = tag_author.get("content").strip()
                break

        # ================= DATE =================
        published_date = None

        date_selectors = [
            ("meta", {"property": "article:published_time"}),
            ("meta", {"property": "og:published_time"}),
            ("meta", {"name": "pubdate"}),
            ("meta", {"name": "publishdate"}),
            ("meta", {"name": "timestamp"}),
            ("meta", {"name": "date"}),
            ("time", {})
        ]

        for tag_name, attrs in date_selectors:
            tag_date = soup.find(tag_name, attrs=attrs)
            if tag_date:
                if tag_name == "meta" and tag_date.get("content"):
                    published_date = tag_date["content"].strip()
                    break
                elif tag_name == "time":
                    if tag_date.get("datetime"):
                        published_date = tag_date["datetime"].strip()
                        break
                    elif tag_date.get_text(strip=True):
                        published_date = tag_date.get_text(strip=True)
                        break

        # ================= JSON-LD =================
        scripts = soup.find_all("script", type="application/ld+json")

        for script in scripts:
            try:
                if not script.string:
                    continue

                data = json.loads(script.string)

                if isinstance(data, dict):
                    data_list = [data]
                elif isinstance(data, list):
                    data_list = data
                else:
                    continue

                for item in data_list:
                    if not isinstance(item, dict):
                        continue

                    if not title and item.get("headline"):
                        title = item["headline"]

                    if not summary and item.get("description"):
                        summary = item["description"]

                    if not published_date and item.get("datePublished"):
                        published_date = item["datePublished"]

                    if not authors and item.get("author"):
                        author_data = item["author"]

                        if isinstance(author_data, dict):
                            authors = author_data.get("name")

                        elif isinstance(author_data, list):
                            names = []
                            for a in author_data:
                                if isinstance(a, dict) and a.get("name"):
                                    names.append(a["name"])
                            if names:
                                authors = ", ".join(names)

            except:
                pass

        # ================= CONTENT =================
        paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
        paragraphs = [p for p in paragraphs if len(p) > 20]
        content = "\n".join(paragraphs)

        if not content.strip():
            raise Exception("Content kosong")

        article_details_list.append({
            "No": no,
            "title": clean_text(title),
            "authors": clean_text(authors),
            "source": clean_text(source),
            "published_date": clean_text(published_date),
            "summary": clean_text(summary),
            "content": clean_text(content),
            "url": url,
            "Sentiment": sentiment,
            "Penerbit": clean_text(penerbit),
            "Tag": tag
        })

        print("   ✔ Berhasil")
        time.sleep(random.uniform(2, 5))

    except Exception as e:
        print(f"   ✖ Gagal | {e}")
        failed_list.append({
            "No": no,
            "Link": url,
            "Sentiment": sentiment,
            "Penerbit": penerbit if pd.notna(penerbit) else urlparse(url).netloc.replace("www.", ""),
            "Tag": tag,
            "cause": str(e)
        })

df_content = pd.DataFrame(article_details_list)
df_failed = pd.DataFrame(failed_list)

# urutkan kolom biar rapi
if not df_failed.empty:
    df_failed = df_failed[["No", "Link", "Sentiment", "Penerbit", "Tag", "cause"]]

print("\nHASIL:")
print("Berhasil:", len(df_content))
print("Gagal   :", len(df_failed))

display(df_content.head())
display(df_failed.head())

[1/100] https://rejogja.republika.co.id/berita/ta8twq282/menkes-pastikan-bpjs-lakukan-sosialisasi-jika-kepesertaan-pbi-jkn-kembali-berubah
   ✔ Berhasil
[2/100] https://www.kompas.tv/regional/655861/urus-pemindahan-data-desil-bpjs-pbi-oknum-asn-dinsos-lebak-lakukan-pungli-ke-warga
   ✔ Berhasil
[3/100] https://www.gesuri.id/pemerintahan/bpjs-pbi-nonaktif-warga-landak-kesulitan-berobat-mengadu-ke-cornelis-b2pQoZbewe
   ✔ Berhasil
[4/100] https://nasional.kompas.com/read/2026/03/09/20240271/peserta-bpjs-pbi-yang-dinonaktifkan-masih-bisa-terlayani-selama-lebaran-2026
   ✔ Berhasil
[5/100] https://bantulkab.go.id/berita/detail/7383/diskominfo@bantulkab.go.id
   ✔ Berhasil
[6/100] https://www.kompas.tv/nasional/650201/dpr-bahas-kisruh-pbi-dinonaktifkan-ini-klarifikasi-menkes-dirut-bpjs-kesehatan
   ✔ Berhasil
[7/100] https://bansos.medanaktual.com/kenapa-kepesertaan-pbi-bpjs-bisa-dinonaktifkan-ini-penjelasannya/
   ✔ Berhasil
[8/100] https://health.detik.com/berita-detikhealth/d-8392134/bpjs-kesehatan-pastikan-peserta-pbi-yang-sempat-nonaktif-tetap-dilayani-selama-mudik
   ✔ Berhasil
[9/100] https://pekanbaru.tribunnews.com/riau-region/1102392/dinsos-kampar-ungkap-penonaktifan-47-ribuan-bpjs-pbi-karena-desil-tiap-daerah-disamaratakan
   ✔ Berhasil
[10/100] https://finansial.bisnis.com/read/20260310/215/1959312/dirut-baru-bpjs-kesehatan-peserta-pbi-nonaktif-berpenyakit-kronis-tetap-bisa-pakai-jkn-saat-mudik
   ✔ Berhasil
[11/100] https://www.radarbangsa.com/news/59453/bpjs-kesehatan-pastikan-peserta-pbi-nonaktif-tetap-dilayani-selama-mudik
   ✔ Berhasil
[12/100] https://koran-jakarta.com/2026-03-10/bpjs-kesehatan-tegaskan-peserta-pbi-nonaktif-tetap-dilayani-selama-mudik
   ✔ Berhasil
[13/100] https://www.oborkeadilan.com/bpjs-kesehatan-jamin-layanan-terus-untuk-peserta-pbi-yang-nonaktif-selama-mudik-lebaran
   ✔ Berhasil
[14/100] https://news.ddtc.co.id/berita/nasional/1817220/11-juta-orang-dihapus-dari-daftar-pbi-jkn-purbaya-usul-begini
   ✔ Berhasil
[15/100] https://video.tribunnews.com/news/911123/rieke-sentil-menkeu-purbaya-soal-data-bpjs-pbi-ini-bukan-kondisi-yang-baik-baik-saja
   ✔ Berhasil
[16/100] https://dprd.kuningankab.go.id/berita/bpjs-pbi-dinonaktifkan-dprd-kuningan-minta-warga-tak-panik-dan-segera-perbarui-data
   ✔ Berhasil
[17/100] https://rejogja.republika.co.id/berita/ta1k4p282/34143-peserta-pbi-bpjs-di-sleman-dinonaktifkan-alasannya-tak-lagi-masuk-desil-15
   ✔ Berhasil
[18/100] https://www.kompas.tv/nasional/649962/relawan-kesehatan-kritik-persoalan-penonaktifan-pbi-data-kita-tidak-terintegrasi-penuh
   ✔ Berhasil
[19/100] https://pers.droneemprit.id/sentimen-publik-terhadap-penonaktifan-pbi-bpjs-kesehatan/
   ✔ Berhasil
[20/100] https://nasional.kompas.com/read/2020/07/02/12012541/pemerintah-pusat-akan-tanggung-iuran-pbi-bpjs-kesehatan-tahun-ini
   ✔ Berhasil
[21/100] https://partainasdem.id/2026/03/09/kebijakan-pbi-bpjs-kesehatan-tidak-boleh-abaikan-masyarakat-rentan/
   ✔ Berhasil
[22/100] https://harianjurnal.com/opini/10211-penonaktifan-peserta-bpjs-kategori-pbi-bijakkah
   ✔ Berhasil
[23/100] https://manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3534-update-data-supaya-penerima-pbi-bpjs-kesehatan-tepat-sasaran
   ✖ Gagal | 523 Server Error: <none> for url: https://manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3534-update-data-supaya-penerima-pbi-bpjs-kesehatan-tepat-sasaran
[24/100] https://www.telusur.co.id/detail/antara-opini-dan-ambisi-sorotan-terhadap-sikap-putu-artha-dalam-polemik-kebijakan-bpjs-pbi
   ✔ Berhasil
[25/100] https://narasipost.com/opini/02/2026/karut-marut-bpjs-pbi-mengancam-kesehatan-rakyat/
   ✔ Berhasil
[26/100] https://www.tintahijau.com/literasi/opini-kisruh-pbi-bpjs-kesehatan/
   ✔ Berhasil
[27/100] https://www.tangerangnews.com/opini/read/57249/Ironi-BPJS-PBI-Melayani-Setengah-Hati
   ✔ Berhasil
[28/100] https://smeru.or.id/id/research-id/kajian-dampak-bantuan-iuran-program-jaminan-kesehatan-pada-masyarakat-miskin-dan-tidak
   ✔ Berhasil
[29/100] https://www.cna.id/indonesia/bpjs-pbi-tetap-aktif-tiga-bulan-dpr-44256
   ✔ Berhasil
[30/100] https://www.manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3176-dampak-pandemi-ratusan-peserta-bpjs-mandiri-minta-pindah-ke-pbi
   ✔ Berhasil
[31/100] https://beritaopini.id/2026/02/13/bpjs-pbi-dinonaktifkan-massal-mahasiswa-aktivis-hingga-ojol-nilai-negara-abai-hak-kesehatan-warga/
   ✔ Berhasil
[32/100] https://gatradewata.com/bangga-angka-miskin-rendah-bpjs-pbi-dihapus-kok-dihidupkan-lagi-dari-apbd-gung-de-konyol/
   ✔ Berhasil
[33/100] https://beritamerdeka.net/news/terbantu-jkn-petani-aceh-selatan-tak-khawatir-biaya-perawatan/index.html
   ✔ Berhasil
[34/100] https://www.antaranews.com/berita/5413874/layanan-bpjs-pbi-tak-terhenti-warga-bersyukur-anaknya-bisa-cuci-darah
   ✔ Berhasil
[35/100] https://denpasar.kompas.com/read/2026/02/10/164359578/walkot-denpasar-aktifkan-bpjs-pbi-masyarakat-merasa-sangat-terbantu?page=all
   ✔ Berhasil
[36/100] https://www.tribun-maluku.com/edukasi-kepesertaan-pbi-jk-di-masohi-bpjs-kesehatan-kolaborasi-dengan-instansi-terkait/03/04/
   ✔ Berhasil
[37/100] https://www.metrotvnews.com/play/kqYCdGde-reaktivasi-sementara-11-juta-peserta-bpjs-pbi-benarkah-sudah-cukup-beranda-nasional
   ✔ Berhasil
[38/100] https://infopublik.id/kategori/nasional-sosial-budaya/958183/index.html
   ✔ Berhasil
[39/100] https://www.harianjogja.com/read/2026/03/04/652/1248230/terbantu-jkn-pensiunan-ini-jalani-cuci-darah-tanpa-hambatan
   ✔ Berhasil
[40/100] https://www.tempo.co/politik/pemerintah-aktifkan-kembali-625-ribu-penerima-bpjs-kesehatan-2125728
   ✔ Berhasil
[41/100] https://www.metrotvnews.com/read/NOlC9PVv-mensos-verifikasi-11-juta-pbi-jkn-sudah-98-persen
   ✔ Berhasil
[42/100] https://www.theindonesianinstitute.com/policy-talks-solusi-penonaktifan-kepesertaan-pbi-bpjs-kesehatan/
   ✔ Berhasil
[43/100] https://www.medcom.id/ekonomi/bisnis/RkjBMx6k-mulai-2021-peserta-pbi-bpjs-kesehatan-ditanggung-pemerintah-pusat
   ✔ Berhasil
[44/100] https://www.geriatri.co.id/artikel/2683/penyebab-bpjs-kesehatan-pbi-tidak-aktif-dan-cara-mengaktifkan-kembali
   ✔ Berhasil
[45/100] https://www.netralnews.com/11013-peserta-pbi-bpjs-nonaktif-di-kuansing-akan-diverifikasi/TUlzUXlvcTkwTkJHYUNtYzYvaE5IZz09
   ✔ Berhasil
[46/100] https://suarantb.com/2026/03/28/kurangi-beban-fiskal-daerah-lobar-usulkan-68-ribu-warga-jadi-pbi-bjps-kesehatan/
   ✔ Berhasil
[47/100] https://faktakalbar.id/2026/03/31/izin-kemenkes-turun-layanan-cuci-darah-rsud-landak-terkendala-kerja-sama-bpjs/
   ✔ Berhasil
[48/100] https://aceh.antaranews.com/berita/403810/pemprov-aceh-keluarkan-tiga-kelompok-masyarakat-dari-penerima-program-jka
   ✔ Berhasil
[49/100] https://pekanbaru.tribunnews.com/riau-region/1102015/hamidah-kini-berhenti-kontrol-ke-dokter-kepesertaan-pbi-tak-kunjung-diaktifkan
   ✔ Berhasil
[50/100] https://bantal.desa.id/artikel/2022/04/20/bpjs-kesehatan-tidak-menanggung-layanan-dan-penyakit-jenis-ini-lihat-daftarnya
   ✔ Berhasil
[51/100] https://www.suarakeadilan.org/id/publikasi/suara-keadilan/lintas-berita/166-mempertanyakan-akses-rakyat-miskin-terhadap-jaminan-kesehatan-nasional
   ✔ Berhasil
[52/100] https://info.medanaktual.com/kenapa-status-pbi-bpjs-berubah-jadi-nonaktif-yuk-cari-tahu-penyebabnya/
   ✔ Berhasil
[53/100] https://www.kompas.tv/nasional/649605/13-5-juta-peserta-bpjs-pbi-dinonaktifkan-mensos-tak-ada-yang-dikurangi-tapi-direalokasi
   ✔ Berhasil
[54/100] https://korankaltara.com/pbi-bpjs-banyak-tidak-aktif-warga-diminta-lapor
   ✔ Berhasil
[55/100] https://www.antaranews.com/berita/1026716/kenaikan-iuran-bpjs-kesehatan-tidak-kurangi-peserta-pbi-di-mataram
   ✔ Berhasil
[56/100] https://www.inibalikpapan.com/bpjs-pbi-tak-dihentikan-dpr-pastikan-warga-miskin-tetap-dilayani-selama-3-bulan-ke-depan/
   ✔ Berhasil
[57/100] https://setkab.go.id/sidak-presiden-jokowi-temukan-lebih-banyak-peserta-bpjs-kesehatan-mandiri-daripada-pbi/
   ✔ Berhasil
[58/100] https://pekanbaru.tribunnews.com/riau-region/1101984/pasien-pbi-bpjs-belum-diaktifkan-terpaksa-beralih-ke-obat-herbal-belum-bisa-kontrol-rutin
   ✔ Berhasil
[59/100] https://www.metrotvnews.com/play/NnjCWMGW-warga-bekasi-dan-depok-padati-kantor-bpjs-untuk-mengaktifkan-kembali-pbijk
   ✔ Berhasil
[60/100] https://nasional.kompas.com/read/2026/02/09/18401521/purbaya-kesal-bpjs-kesehatan-pbi-mendadak-dinonaktifkan-konyol-saya-rugi?page=all
   ✔ Berhasil
[61/100] https://era.id/nasional/183383/pbi-non-aktif-picu-kemarahan-publik-bpjs-kesehatan-lempar-bola-panas-ke-rumah-sakit
   ✔ Berhasil
[62/100] https://video.kompas.com/live/34808b196bdf5d3571cb2faf7a64ed9c/polemik-penonaktifan-bpjs-kesehatan-pbi-apa-jalan-keluarnya-obrolan-newsroom
   ✔ Berhasil
[63/100] https://www.kompas.tv/nasional/649954/kisruh-bpjs-kesehatan-pbi-warga-dinonaktifkan-kemensos-lakukan-perombakan-kompas-siang
   ✔ Berhasil
[64/100] https://www.tempo.co/ekonomi/bos-bpjs-kesehatan-jelaskan-alasan-7-3-juta-peserta-pbi-jkn-dinonaktifkan-1795353
   ✔ Berhasil
[65/100] https://jogja.antaranews.com/berita/819773/bpjs-kesehatan-bayi-baru-lahir-dari-orang-tua-terdaftar-pbi-ditanggung-jkn
   ✔ Berhasil
[66/100] https://wartakota.tribunnews.com/jakarta/882723/cerita-tia-bolak-balik-urus-bpjs-pbi-akui-kesal-karena-dinonaktifkan-tanpa-pemberitahuan?page=all
   ✔ Berhasil
[67/100] https://pojokbanua.com/penyebab-polemik-bpjs-pbi-bagaimana-nasib-pasien-penyakit-berat/
   ✔ Berhasil
[68/100] https://www.kompas.id/artikel/bpjs-kesehatan-pbi-milik-11-juta-warga-miskin-di-jateng-dinonaktifkan
   ✔ Berhasil
[69/100] https://www.kompas.id/artikel/11-juta-peserta-pbi-jkn-dinonaktifkan-lebih-dari-100-pasien-cuci-darah-terdampak
   ✔ Berhasil
[70/100] https://nasional.kontan.co.id/news/bpjs-kesehatan-catat-jumlah-peserta-pbi-968-juta-pengobatan-jantung-meningkat
   ✔ Berhasil
[71/100] https://www.sinarharapan.net/kartu-pbi-tak-berlaku-pasien-miskin-tak-dapat-layanan-kesehatan/
   ✔ Berhasil
[72/100] https://headlinekaltim.co/jarang-dipakai-berobat-apakah-benar-bpjs-kesehatan-pbi-bisa-diblokir/
   ✔ Berhasil
[73/100] https://karangmulyo.kendalkab.go.id/kabardetail/d2dsNjloV2JZTFBEN2lSZUN1ZkhJUT09/segera-manfaatkan-bpjs-pbi-anda-minimal-3-bulan-sekali.html
   ✔ Berhasil
[74/100] https://www.surabaya.go.id/id/berita/73952/pemkot-surabaya-imbau-peserta-pbi-jk-yang-tak-aktif-ajukan-pendaftaran-pbpu
   ✔ Berhasil
[75/100] https://www.bpjsketenagakerjaan.go.id/berita/29164/Edy-Dorong-Kolaborasi-Untuk-Realisasikan-PBI-Untuk-Jamsostek
   ✔ Berhasil
[76/100] https://www.bpjsketenagakerjaan.go.id/berita/27725/Kajian-aturan-PBI-jamsosketenagakerjaan-ditargetkan-rampung-tahun-ini
   ✔ Berhasil
[77/100] https://www.manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3807-benarkah-warga-yang-tak-daftar-bpjs-kesehatan-akan-otomatis-terdaftar-kategori-pbi
   ✔ Berhasil
[78/100] https://kemkes.go.id/id/penerima-bantuan-iuran-pbi-jaminan-kesehatan-nasional-jkn-di-daerah-istimewa-yogyakarta-sebanyak-1-572-154-jiwa
   ✔ Berhasil
[79/100] https://nasional.kontan.co.id/news/bpjs-kesehatan-sebut-tak-ada-tambahan-peserta-penerima-bantuan-iuran-pbi-kesehatan
   ✔ Berhasil
[80/100] https://www.antaranews.com/berita/3329355/kemensos-disabilitas-mental-diizinkan-jadi-peserta-pbi-bpjs-kesehatan
   ✔ Berhasil
[81/100] https://www.pasuruankab.go.id/isiberita/37-495-peserta-pbin-di-kabupaten-pasuruan-dinonaktifkan
   ✔ Berhasil
[82/100] https://www.tangerangkota.go.id/berita/detail/37237/wujudkan-pengobatan-kesehatan-gratis-pemkot-tangerang-bayarkan-367-476-warga-iuran-bpjs-kesehatan
   ✔ Berhasil
[83/100] https://news.republika.co.id/berita/t9zkne458/ramai-pbi-jk-mendadak-nonaktif-mensos-rs-tak-boleh-menolak-pasien-cuci-darah
   ✔ Berhasil
[84/100] https://health.detik.com/berita-detikhealth/d-8340126/30-pasien-cuci-darah-tak-bisa-berobat-imbas-status-pbi-bpjs-mendadak-non-aktif
   ✔ Berhasil
[85/100] https://www.cnnindonesia.com/ekonomi/20260209173925-532-1326288/purbaya-soal-peserta-pbi-bpjs-cuci-darah-dinonaktifkan-kita-konyol
   ✔ Berhasil
[86/100] https://www.netralnews.com/heboh-bpjs-kesehatan-pbi-tiba-tiba-nonaktif-ini-penjelasan-resminya/ZFJ2TFdxWnZaQzg3bEZXTVlGMk5zUT09
   ✔ Berhasil
[87/100] https://www.liputan6.com/bisnis/read/6273347/ylki-kritik-penonaktifan-peserta-pbi-bpjs-kesehatan-pasien-rentan-jadi-korban
   ✔ Berhasil
[88/100] https://www.kompas.tv/regional/650093/kacau-penonaktifan-13-5-juta-peserta-bpjs-pbi-picu-masalah-layanan-kesehatan-di-berbagai-daerah
   ✔ Berhasil
[89/100] https://voi.id/bernas/558547/karut-marut-penonaktifan-peserta-bpjs-pbi-pemerintah-tak-pernah-mau-belajar
   ✔ Berhasil
[90/100] https://www.bloombergtechnoz.com/detail-news/54933/kronologi-ancaman-gagal-bayar-bpjs-kesehatan-iuran-naik
   ✔ Berhasil
[91/100] https://www.bbc.com/indonesia/articles/cn06g268n6vo
   ✔ Berhasil
[92/100] https://fkkmk.ugm.ac.id/penyakit-jantung-dan-kanker-25-persen-duduki-pembiayaan-bpjs-kesehatan/
   ✔ Berhasil
[93/100] https://www.liputan6.com/hot/read/5714785/bantuan-pbi-adalah-solusi-kesehatan-bagi-masyarakat-kurang-mampu-ini-penjelasannya
   ✔ Berhasil
[94/100] https://jatim.antaranews.com/berita/690537/ada-lima-juta-orang-antre-jadi-peserta-pbi-jkn
   ✔ Berhasil
[95/100] https://www.tempo.co/politik/sederet-fakta-jaminan-kesehatan-11-juta-orang-dicabut-2113363
   ✔ Berhasil
[96/100] https://news.detik.com/berita/d-8343050/dirut-bpjs-buka-suara-usai-ramai-status-pbi-jk-warga-mendadak-nonaktif
   ✔ Berhasil
[97/100] https://www.tempo.co/ekonomi/mengenal-apa-itu-pbi-jk-serta-kriteria-penerimanya-1189453
   ✔ Berhasil
[98/100] https://finansial.bisnis.com/read/20260331/215/1963398/625221-peserta-bpjs-kesehatan-pbi-dapat-pemulihan-verifikasi-data-sudah-98
   ✔ Berhasil
[99/100] https://banten.antaranews.com/berita/377374/500-warga-kota-serang-reaktivasi-bpjs-pbi-dari-11000-data-nonaktif
   ✔ Berhasil
[100/100] https://nasional.kompas.com/read/2020/05/15/10194671/berbagai-alasan-dan-klaim-pemerintah-naikkan-iuran-bpjs-kesehatan
   ✔ Berhasil

HASIL:
Berhasil: 99
Gagal   : 1

,No,title,authors,source,published_date,summary,content,url,Sentiment,Penerbit,Tag
0,1,Menkes Pastikan BPJS Lakukan Sosialisasi Jika ...,Karta Raharja Ucu,rejogja.republika.co.id,2026-02-10T19:41:14+07:00,PBI JKN hendak difokuskan kepada yang memang b...,PBI JKN hendak difokuskan kepada yang memang b...,https://rejogja.republika.co.id/berita/ta8twq2...,Netral,rejogja.republika.co.id,Kebijakan
1,2,"Urus Pemindahan Data Desil BPJS PBI, Oknum ASN...",Yulian Indah,kompas.tv,2026-03-10 13:12:18+00:00,"Seorang ASN Dinas Sosial Kabupaten Lebak, Bant...",KOMPAS.TV - Seorang ASN Dinas Sosial Kabupaten...,https://www.kompas.tv/regional/655861/urus-pem...,Negatif,kompas.tv,Sosial
2,3,"BPJS PBI Nonaktif, Warga Landak Kesulitan Bero...",www.gesuri.id,gesuri.id,2026-03-10 11:46:42,Penonaktifan dilakukan tanpa pemberitahuan sos...,"Landak, Gesuri.id - Warga kurang mampu mendada...",https://www.gesuri.id/pemerintahan/bpjs-pbi-no...,Negatif,gesuri.id,Pelayanan
3,4,Peserta BPJS PBI yang Dinonaktifkan Masih Bisa...,Kompas Cyber Media,nasional.kompas.com,2026-03-09T13:24:02+00:00,Peserta BPJS Kesehatan PBI tetap terlayani saa...,Peserta BPJS PBI yang Dinonaktifkan Masih Bisa...,https://nasional.kompas.com/read/2026/03/09/20...,Positif,nasional.kompas.com,Kebijakan
4,5,"Peserta PBI JKN Dinonaktifkan, BPJS Kesehatan ...",None,bantulkab.go.id,None,Website Public,Belakangan ini masyarakat ramai membicarakan k...,https://bantulkab.go.id/berita/detail/7383/dis...,Netral,bantulkab.go.id,Kebijakan

,No,Link,Sentiment,Penerbit,Tag,cause
0,23,https://manajemen-pembiayaankesehatan.net/inde...,Netral,manajemen-pembiayaankesehatan.net,Kebijakan,523 Server Error: <none> for url: https://mana...

In [ ]:
import csv

# CSV
df_content.to_csv(
    "/content/drive/MyDrive/df_shafa_1.csv",
    index=False,
    encoding="utf-8-sig",
    quoting=csv.QUOTE_ALL
)

In [ ]:
list_of_urls = df_failed['Link'].tolist()
list_of_urls

['https://manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3534-update-data-supaya-penerima-pbi-bpjs-kesehatan-tepat-sasaran']

In [ ]:
from os import link
import requests
import pandas as pd
from bs4 import BeautifulSoup
from urllib.parse import urlparse
import time
import json
import re
import random

session = requests.Session()

headers_list = [
    {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive"
    },
    {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
        "Accept-Language": "id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive"
    }
]

article_details_list = []
failed_list = []
headers = random.choice(headers_list)


def clean_text(text):
    if text is None:
        return None
    text = str(text)
    text = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text if text else None


for i, row in df_failed.iterrows():
    no = row.get("No")
    url = row.get("Link")
    sentiment = row.get("Sentiment")
    penerbit = row.get("Penerbit")
    tag = row.get("Tag")

    print(f"[{i+1}/{len(df_failed)}] {url}")

    try:
        r = session.get(url, headers=headers, timeout=30)
        r.raise_for_status()

        soup = BeautifulSoup(r.text, "html.parser")
        source = urlparse(url).netloc.replace("www.", "")

        # kalau kolom Penerbit kosong, pakai domain URL
        if pd.isna(penerbit) or not str(penerbit).strip():
            penerbit = source

        # ================= TITLE =================
        title = None

        if soup.title:
            title = soup.title.get_text(" ", strip=True)

        og_title = soup.find("meta", attrs={"property": "og:title"})
        if og_title and og_title.get("content"):
            title = og_title["content"].strip()

        # ================= SUMMARY =================
        summary = None

        meta_desc = soup.find("meta", attrs={"name": "description"})
        if meta_desc and meta_desc.get("content"):
            summary = meta_desc["content"].strip()

        if not summary:
            og_desc = soup.find("meta", attrs={"property": "og:description"})
            if og_desc and og_desc.get("content"):
                summary = og_desc["content"].strip()

        # ================= AUTHORS =================
        authors = None

        author_selectors = [
            ("meta", {"name": "author"}),
            ("meta", {"property": "author"}),
            ("meta", {"name": "article:author"}),
            ("meta", {"property": "article:author"})
        ]

        for tag_name, attrs in author_selectors:
            tag_author = soup.find(tag_name, attrs=attrs)
            if tag_author and tag_author.get("content"):
                authors = tag_author.get("content").strip()
                break

        # ================= DATE =================
        published_date = None

        date_selectors = [
            ("meta", {"property": "article:published_time"}),
            ("meta", {"property": "og:published_time"}),
            ("meta", {"name": "pubdate"}),
            ("meta", {"name": "publishdate"}),
            ("meta", {"name": "timestamp"}),
            ("meta", {"name": "date"}),
            ("time", {})
        ]

        for tag_name, attrs in date_selectors:
            tag_date = soup.find(tag_name, attrs=attrs)
            if tag_date:
                if tag_name == "meta" and tag_date.get("content"):
                    published_date = tag_date["content"].strip()
                    break
                elif tag_name == "time":
                    if tag_date.get("datetime"):
                        published_date = tag_date["datetime"].strip()
                        break
                    elif tag_date.get_text(strip=True):
                        published_date = tag_date.get_text(strip=True)
                        break

        # ================= JSON-LD =================
        scripts = soup.find_all("script", type="application/ld+json")

        for script in scripts:
            try:
                if not script.string:
                    continue

                data = json.loads(script.string)

                if isinstance(data, dict):
                    data_list = [data]
                elif isinstance(data, list):
                    data_list = data
                else:
                    continue

                for item in data_list:
                    if not isinstance(item, dict):
                        continue

                    if not title and item.get("headline"):
                        title = item["headline"]

                    if not summary and item.get("description"):
                        summary = item["description"]

                    if not published_date and item.get("datePublished"):
                        published_date = item["datePublished"]

                    if not authors and item.get("author"):
                        author_data = item["author"]

                        if isinstance(author_data, dict):
                            authors = author_data.get("name")

                        elif isinstance(author_data, list):
                            names = []
                            for a in author_data:
                                if isinstance(a, dict) and a.get("name"):
                                    names.append(a["name"])
                            if names:
                                authors = ", ".join(names)

            except:
                pass

        # ================= CONTENT =================
        paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
        paragraphs = [p for p in paragraphs if len(p) > 20]
        content = "\n".join(paragraphs)

        if not content.strip():
            raise Exception("Content kosong")

        article_details_list.append({
            "No": no,
            "title": clean_text(title),
            "authors": clean_text(authors),
            "source": clean_text(source),
            "published_date": clean_text(published_date),
            "summary": clean_text(summary),
            "content": clean_text(content),
            "url": url,
            "Sentiment": sentiment,
            "Penerbit": clean_text(penerbit),
            "Tag": tag
        })

        print("   ✔ Berhasil")
        time.sleep(random.uniform(2, 5))

    except Exception as e:
        print(f"   ✖ Gagal | {e}")
        failed_list.append({
            "No": no,
            "Link": url,
            "Sentiment": sentiment,
            "Penerbit": penerbit if pd.notna(penerbit) else urlparse(url).netloc.replace("www.", ""),
            "Tag": tag,
            "cause": str(e)
        })

df_content = pd.DataFrame(article_details_list)
df_failed = pd.DataFrame(failed_list)

# urutkan kolom biar rapi
if not df_failed.empty:
    df_failed = df_failed[["No", "Link", "Sentiment", "Penerbit", "Tag", "cause"]]

print("\nHASIL:")
print("Berhasil:", len(df_content))
print("Gagal   :", len(df_failed))

display(df_content.head())
display(df_failed.head())

[1/1] https://manajemen-pembiayaankesehatan.net/index.php/berita-nasional/3534-update-data-supaya-penerima-pbi-bpjs-kesehatan-tepat-sasaran
   ✔ Berhasil

HASIL:
Berhasil: 1
Gagal   : 0

,No,title,authors,source,published_date,summary,content,url,Sentiment,Penerbit,Tag
0,23,Update Data supaya Penerima PBI BPJS Kesehatan...,Super User,manajemen-pembiayaankesehatan.net,None,Manajemen Pembiayaan Kesehatan,JawaPos.com – Lebih dari 95 persen warga Surab...,https://manajemen-pembiayaankesehatan.net/inde...,Netral,manajemen-pembiayaankesehatan.net,Kebijakan

Empty DataFrame
Columns: []
Index: []

In [ ]:
import csv

# CSV
df_content.to_csv(
    "/content/drive/MyDrive/df_shafa_2.csv",
    index=False,
    encoding="utf-8-sig",
    quoting=csv.QUOTE_ALL
)